title : PEQNP
description : PEQNP Mathematical Solver
logo : https://raw.githubusercontent.com/maxtuno/PEQNP/master/logo.png
theme: jekyll-theme-leap-day
google_analytics : UA-146115776-2
show_downloads : true
