title: PEQNP
description: A Multi-Paradigm Constraint Satisfaction Solver.
logo : https://raw.githubusercontent.com/maxtuno/PEQNP/master/logo.png
theme: jekyll-theme-minimal
google_analytics: UA-146115776-2
